# Estágio Único: Servir Estáticos
# Assumes que 'npm run build' já foi rodado localmente e a pasta 'dist' existe
FROM nginx:alpine

# Copia o resultado da build local para o Nginx
COPY dist /usr/share/nginx/html

# Expõe a porta 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
